### ISSUE TITLE
Swift delegate error

### ISSUE THREAD

**Issue by iTSangar** [atljeremy/JFMinimalNotifications#22]
I'm using pod with Swift and everything works fine until...

In first time when I tried delegate methods worked (using following code), but for unknown reason, in others attempts delegate property lose reference and don't respond anymore:

```swift
class Notifications: NSObject, JFMinimalNotificationDelegate {
  
  private var minimalNotification: JFMinimalNotification!

  override init() {
    super.init()
    minimalNotification = JFMinimalNotification(style: JFMinimalNotificationStyle.Error,
        title: " ",
        subTitle: " ",
        dismissalDelay: NSTimeInterval(1.5))
    minimalNotification.presentFromTop = true
    minimalNotification.delegate = self
  }

func showNotificationType(style:JFMinimalNotificationStyle, controller: UIViewController, title: String, subtitle: String) {
    minimalNotification.setStyle(style, animated: true)
    minimalNotification?.titleLabel.text = title
    minimalNotification?.subTitleLabel.text = subtitle
    controller.view.addSubview(minimalNotification)
    minimalNotification.show()
  }


@objc func minimalNotificationWillShowNotification(notification: JFMinimalNotification!) {
   // call because delegate property in JFMinimalNotification.m not is nil yet
  }

@objc func minimalNotificationDidDismissNotification(notification: JFMinimalNotification!) {
   // don't call because delegate property in JFMinimalNotification.m is turned nil
  }
```

**Comment by atljeremy** [comment]
This is likely happening due to not retaining your `Notification` class instance in your code. I can see it's not a singleton, so where are you creating an instance of this class and how are you retaining it? Have you tried profiling your app to see if the `Notification` instance you think is still alive is actually being deallocated? Also, the JFMinimalNotificationDelegate is defined as a `weak` property and therefore will not retain the delegate. https://github.com/atljeremy/JFMinimalNotifications/blob/master/JFMinimalNotification/JFMinimalNotification.h#L80

Please profile your code and make sure your `Notification` instance isn't being deallocated and let me know what you've found.

**Comment by iTSangar** [comment]
You're right, I was losing references from my instance. Thanks for the reply.
All work fine now
