### ISSUE TITLE
Long subtitle message

### ISSUE THREAD

**Issue by isayeter** [atljeremy/JFMinimalNotifications#37]
Hello, thanks for this amazing class.

When I want to show a very long subtitle message, it looks like this:

![aaa](https://cloud.githubusercontent.com/assets/3602109/21825598/06ea7b00-d78d-11e6-8612-7cecfa36cc0f.jpg)

as you see, it is impossinle to read that.

When I added 

````
self.subTitleLabel.numberOfLines = 3;
`````

before this line : https://github.com/atljeremy/JFMinimalNotifications/blob/master/JFMinimalNotification/JFMinimalNotification.m#L457

it becomes this:

![bbb](https://cloud.githubusercontent.com/assets/3602109/21825627/24a5f476-d78d-11e6-9955-df6af05bdde0.jpg)

If you say this is ok, please update your wonderful code.

Thanks.

**Comment by TiLodoss** [comment]
Do we have any update on this issue? It would be great to have this fix in the Pod, to support long subtitles messages. Thanks!

**Comment by atljeremy** [comment]
Both `titleLabel` and `subtitleLabel` have accessible getters so you can customize them however you'd like. The notification itself will not set `numberOfLines` internally for either label to avoid making any sort of assumptions about what will be presented. Since you have full control, you can change it however you'd like.
