### ISSUE TITLE
the alert can' dismiss

### ISSUE THREAD

**Issue by whitefox0102** [atljeremy/JFMinimalNotifications#39]
When I show the notification and wait for it to disappear automatically, I dismiss the View and I will see that the notification still exists at the top.

https://imgur.com/UZsU7Mn
https://imgur.com/4FWk2yN
https://imgur.com/Xu4s9gq

please help me~~
thanks

**Comment by atljeremy** [comment]
Super late response here, sorry about that. I can't view the images but what you're describing sounds like the expected behavior. Calling `dismiss` simply animates the layout constraints to hide it outside of the visual frame area. The notification doesn't remove itself from the superview, that's up to you to handle. For example, whenever you want it removed from the view hierarchy, simply call `notification.removeFromSuperview()`. You probably don't want to do that every time you dismiss the notification. It would likely be best to just remove it in `deinit` of the view/view controller where you're presenting it.
