### ISSUE TITLE
Changing title or subtitle text 

### ISSUE THREAD

**Issue by Jayvd** [atljeremy/JFMinimalNotifications#8]
How do we cahnge the title or subtitleLabel text?

self.minimalNotification.titleLabel.text = "New String" // Crashes

Thank you

**Comment by atljeremy** [comment]
Currently, you don't. The notifications and initialized with a title and subtitle and they are readonly after that. I can look into adding the ability to change the labels text.

**Comment by atljeremy** [comment]
OK so, I'm not sure what I was thinking when I wrote my previous reply because you can in-fact change the title and subTitle text when ever you want using code like the following...

```swift
self.notification?.titleLabel.text = "New Title"
self.notification?.subTitleLabel.text = "New Sub-Title"
```

This is a swift example but can easily be adapted for Obj-C. I'm going to close this issue now as this is already possible.

If you are experiencing a crash and you are positivity it's happening inside of JFMinimalNotification source code please reply to this issue and paste in the stack track from the crash log.

**Comment by EzimetYusup** [comment]
@atljeremy  in my case it crashes with this log:

![log](https://cloud.githubusercontent.com/assets/7555642/6660744/30da091a-cbca-11e4-8efc-beea06647044.png)

**Comment by atljeremy** [comment]
Thanks, I'll see if I can reproduce in a Swift project and get it patched.

**Comment by atljeremy** [comment]
@EzimetYusup The issue in your case is that you are initializing an instance of `JFMinimalNotification` without setting a valid string for the title/subtitle. When you do this, the corresponding title/subtitle label is never created/added to the view. This is the reason for `fatal error: unexpectedly found nil while unwrapping an Optional value`. So, as a quick fix for this, if you want to create the notification without an initial title or subtitle just us string containing a single space. Yep, this is an ugly hack but it will allow you to do what you want for now.

Example:
```swift
_notification = JFMinimalNotification(style: .StyleSuccess, title: " ", subTitle: " ", dismissalDelay: 5) { [unowned self] in
    _notification?.dismiss()
}
```

**Comment by atljeremy** [comment]
@Jayvd See my comment above.
